"""initial schema

Revision ID: 9d1ef5ac2f21
Revises: 
Create Date: 2026-07-18 18:40:09.228181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1ef5ac2f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('conversiontype', sa.String(), nullable=False),
    sa.Column('confirmationref', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'dedup_key', name='uq_conversion_dedup')
    )
    op.create_index(op.f('ix_conversions_dedup_key'), 'conversions', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_conversions_merchant_id'), 'conversions', ['merchant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_job_id'), 'outbox_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_merchant_id'), 'outbox_events', ['merchant_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'policy_version', name='uq_policy_version')
    )
    op.create_index(op.f('ix_policy_versions_merchant_id'), 'policy_versions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_version'), 'policy_versions', ['policy_version'], unique=False)
    op.create_table('replay_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('base_version', sa.String(), nullable=False),
    sa.Column('proposed_version', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_replay_idem')
    )
    op.create_index(op.f('ix_replay_jobs_merchant_id'), 'replay_jobs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replay_jobs_merchant_id'), table_name='replay_jobs')
    op.drop_table('replay_jobs')
    op.drop_index(op.f('ix_policy_versions_policy_version'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_merchant_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_outbox_events_merchant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_job_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_conversions_merchant_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_dedup_key'), table_name='conversions')
    op.drop_table('conversions')
    # ### end Alembic commands ###
